#!/usr/bin/python
import rospy
from opensim_server.recorder import Recorder


def main(frames_list, base_frame):
    rec = Recorder()
    rec.run(frames_list, base_frame)

    new_recording = True
    
    while new_recording and not rospy.is_shutdown():
        rospy.loginfo("Please enter the name of the file to store the recording (do not put the path nor the extension):")
        savefile = raw_input()
        while savefile == "" and not rospy.is_shutdown():
            rospy.loginfo("The file name should at least contain one character. Please enter a valid name:")
            savefile = raw_input()
        
        if rospy.is_shutdown(): return

        rospy.loginfo("Press enter to start recording.")
        raw_input()
        rec.start_recording()

        if rospy.is_shutdown(): return

        rospy.loginfo("Recording... Press enter to stop recording.")
        raw_input()
        filepath = rec.stop_recording(savefile)

        if rospy.is_shutdown(): return

        rospy.loginfo("Recorded data saved in " + filepath + ". Record a new demonstration? y/N:")
        resp = raw_input()
        new_recording = (resp == "y")


if __name__ == '__main__':
    rospy.init_node('kinect_recorder')

    frames_list = ['right_wrist', 'right_hand', 'left_wrist', 'left_hand',
                   'right_ankle', 'right_foot', 'left_ankle', 'left_foot',
                   'head', 'neck', 'shoulder_center', 'spine', 'base',
                   'left_shoulder', 'left_elbow', 'left_hip', 'left_knee',
                   'right_shoulder', 'right_elbow', 'right_hip', 'right_knee']

    for i in range(len(frames_list)):
        frames_list[i] = '/kinect/human/' + frames_list[i]

    base_frame = '/kinect_frame'
    
    main(frames_list, base_frame)
